apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go
spec:
  template:
    spec:
      containers:
        - name: api-go
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
