apiVersion: v1
kind: Service
metadata:
  name: api-java-nonblocking
  labels:
    app: api-java-nonblocking
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: api-java-nonblocking
