apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-java-blocking
spec:
  template:
    spec:
      containers:
        - name: api-java-blocking
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
