apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust
spec:
  template:
    spec:
      containers:
        - name: api-rust
          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "250m"
