apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust
spec:
  template:
    spec:
      containers:
        - name: api-rust
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
